repos:
- repo: https://github.com/pre-commit/mirrors-autopep8
  rev: ''
  hooks:
  - id: autopep8
    exclude: '^$'
    args: [--verbose,  --in-place, --aggressive, --aggressive]

- repo: https://github.com/PyCQA/flake8
  rev: 6.1.0
  hooks:
  - id: flake8
    args: [--ignore=E501,--ignore=F401,--ignore=W504,--max-line-length=150]

- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
  - id: isort

- repo: https://github.com/PyCQA/autoflake
  rev: v2.2.0
  hooks:
  - id: autoflake
    name: autoflake
    entry: autoflake
    language: python
    require_serial: true
    types: [python]
    args:
      [
        --in-place,
        --expand-star-imports,
        --remove-unused-variables,
        --remove-all-unused-imports
      ]